weight/weight/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weightapp/', include('weightapp.urls')),
    path('', include('weightapp.urls')),
]

weight/weightapp/urls.py
from django.urls import path
from . import views

app_name = 'weightapp'
urlpatterns = [
        path('', views.index, name='index'),
        path('<int:year>/<int:month>', views.index, name='index'),
        path('login/', views.Login.as_view(), name='login'),
        path('logout/', views.Logout.as_view(), name='logout'),
        path('line_chart_json/', views.LineChartJSONView.as_view(), name='line_chart_json'),
]

weight/weightapp/models.py
from django.db import models

# Create your models here.
class Weightapp(models.Model):
    use_date = models.DateTimeField('Date & Date')
    weight = models.IntegerField(default=0)
    bodyfat = models.IntegerField(default=0)
    detail = models.CharField(max_length=200)
    category = models.CharField(max_length=10)

    def __str__(self):
        return str(self.use_date) + ' /' + self.detail + ' /' + str(self.weight)

weight/weightapp/forms.py
from bootstrap_datepicker_plus import  DatePickerInput
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm
)

from .models import Weightapp

class RecordingForm(forms.Form):
    choices = (
            ('Leg', 'Leg'),
            ('Shoulder', 'Shoulder'),
            ('Back', 'Back'),
            ('Arm', 'Arm'),
            ('Chest', 'Chest'),
            ('No workouts', 'No workouts')
    )
    use_date = forms.DateField(widget=DatePickerInput(format='%Y/%m/%d'))
    #use_date = forms.DateTimeField(label='Date')
    weight = forms.IntegerField(label='Weight')
    bodyfat = forms.IntegerField(label='Body fat')
    detail = forms.CharField(max_length=2000, label='Detail')
    category = forms.ChoiceField(choices=choices, label='Category')

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

weight/weightapp/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.views import generic

import pytz
import datetime
import calendar
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('tkagg')

from django.views.generic import CreateView, TemplateView
from chartjs.views.lines import BaseLineChartView

from .models import Weightapp
from .forms import RecordingForm, LoginForm

# Create your views here.
class Index(generic.TemplateView):
    template_name = 'weightapp/index.html'

class Login(LoginView):
    form_class = LoginForm
    template_name = 'weightapp/login.html'

class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'weightapp/index.html'

TODAY = str(timezone.now()).split('-')

def index(request, year=TODAY[0], month=TODAY[1]):
    weight = Weightapp.objects.filter(use_date__month=month).order_by('use_date')
    for w in weight:
        date = str(w.use_date).split(' ')[0]
        w.use_date = '/'.join(date.split('-')[1:3])

    form = RecordingForm()
    context = {
        'year' : year,
        'month' : month,
        'weight' : weight,
        'form' : form,
    }

    draw_graph(year, month)

    if request.method == 'POST':
        data = request.POST
        use_date = data['use_date']
        weight = data['weight']
        bodyfat = data['bodyfat']
        detail = data['detail']
        category = data['category']

        use_date = timezone.datetime.strptime(use_date, "%Y/%m/%d")
        sydney_timezone = pytz.timezone('Australia/Sydney')
        use_date = sydney_timezone.localize(use_date)
        use_date += datetime.timedelta(hours=10)

        Weightapp.objects.create(
                    use_date = use_date,
                    weight = int(weight),
                    bodyfat = int(bodyfat),
                    detail = detail,
        )
        return redirect(to='/weightapp/{}/{}'.format(year, month))

    return render(request, 'weightapp/index.html', context)

def draw_graph(year, month):
    weight = Weightapp.objects.filter(use_date__year=year, use_date__month=month).order_by('use_date')

    last_day = calendar.monthrange(int(year), int(month))[1] + 1
    day = [i for i in range(1, last_day)]
    Myweight = [0 for i in range(len(day))]
    for w in weight:
        key = str(w.use_date).split('-')[2]
        Myweight[int(str(key).split(' ')[0])-1] += int(w.weight)
        #Myweight[int(14)-1] += int(w.weight)
        Myweight = [float('nan') if x == 0 else x for x in Myweight]
    plt.figure()
    plt.plot(day, Myweight, color='#00bfff')
    plt.grid(True)
    plt.xlim([0, 31])
    plt.xlabel('Date', fontsize=16)
    plt.ylabel('Weight', fontsize=16)
    plt.savefig('weightapp/static/images/bar_{}_{}.svg'.format(year, month), transparent=True)

    return None

class CreateView(CreateView):
    model = Weightapp
    fields = ('use_date', 'weight', 'bodyfat', 'category', 'detail')

class LineChartJSONView(BaseLineChartView):
    def get_data(self):
        weight = Weightapp.objects.filter(use_date__year=year, use_date__month=month).order_by('use_date')
        return weight

    def get_labels(self):
        last_day = calendar.monthrange(int(2019), int(7))[1] + 1
        day = [i for i in range(1, last_day)]
        return day

line_chart = TemplateView.as_view(template_name='weightapp/line_chart.html')
line_chart_json = LineChartJSONView.as_view()

weight/weightapp/templates/weightapp/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>Registration</title>
</head>
<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'weightapp:index' %}">Weightapp</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'weightapp:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'weightapp:login' %}">
            Welcome to Weightapp! Login
          </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

weight/weightapp/templates/weightapp/index.html
{% load static %}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load crispy_forms_tags %}

{{ form.media }}

<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <title>WeightApp</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{% static 'weightapp/style.css' %}">
    </head>
    <body>
      <nav class="navbar navbar-dark sticky-top bg-info flex-md-nowrap p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">WeightApp</a>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="#">Sign out</a>
          </li>
        </ul>
      </nav>

      <div class="container-fluid">
          <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
              <div class="sidebar-sticky">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link active" href=".">
                      <span data-feather="home"></span>
                      Dashboard <span class="sr-only">(current)</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <span data-feather="file"></span>
                      Training
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <span data-feather="shopping-cart"></span>
                      Meals
                    </a>
                  </li>
                </ul>
              </div>
            </nav>
            <div class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
             <h1 class="h3">Dashboard {{ year }}/{{ month }}</h1>
              <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group mr-2">
                  <button class="btn btn-sm btn-outline-secondary">Share</button>
                  <button class="btn btn-sm btn-outline-secondary">Export</button>
                </div>
                <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                  <span data-feather="calendar"></span>
                  This month
                </button>
              </div>
              </div>

              <canvas class="my-4" id="myChart" width="900" height="380"></canvas>

              <div>
                <img src="/static/images/bar_{{ year }}_{{ month }}.svg" width=70%>
              </div>
              <h1 class="h3">Daily Records</h1>
              <div class="row">
                <div class="col-sm-9">
                  <button type="button" class="btn btn-success bgn-lg" data-toggle="modal" data-target="#myModal">
                    Add
                  </button>
                  <div class="modal" id="myModal">
                    <div class="modal-dialog">
                      <div class="modal-content">

                        <!-- Modal Header -->
                        <div class="modal-header">
                          <h4 class="modal-title">Add data</h4>
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>

                        <!-- Modal body -->
                        <div class="modal-body">
                          <form action="/weightapp/" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-success">Submit</button>
                          </form>
                        </div>
                      </div>
                  </div>
                </div>
              <table class="table">
                <tr>
                  <th>Date</th>
                  <th>Weight (kg)</th>
                  <th>Body Fat (%)</th>
                  <th>Category</th>
                  <th>Details</th>
                </tr>
                {% for w in weight %}
                <tr>
                    <td>{{ w.use_date }}</td>
                    <td>{{ w.weight }}kg</td>
                    <td>{{ w.bodyfat }}%</td>
                    <td>{{ w.category }}</td>
                    <td>{{ w.detail }}</td>
                </tr>
                {% endfor %}
              </table>
              </div>
              </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>

        <script>
          var ctx = document.getElementById("myChart");
          var myChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
              datasets: [{
                data: [90, 91.5, 90.6, 90.4, 90, 90, 89],
                lineTension: 0,
                backgroundColor: 'transparent',
                borderColor: '#007bff',
                borderWidth: 4,
                pointBackgroundColor: '#007bff'
              }]
            },
            options: {
              scales: {
                yAxes: [{
                  ticks: {
                    beginAtZero: false
                  }
                }]
              },
              legend: {
                display: false,
              }
            }
          });
        </script>
    </body>
</html>

weight/weightapp/templates/weightapp/line-chart.html
{% load staticfiles %}
<html>
    <head>
        <title>django-chartjs line chart demo</title>
        <!--[if lte IE 8]>
            <script src="{% static 'js/excanvas.js' %}"></script>
        <![endif]-->
    </head>
    <body>
        <h1>Some Line Charts loaded in Ajax!</h1>

        <canvas id="myChart" width="500" height="400"></canvas>

        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
        <script type="text/javascript">
            $.get('{% url "line_chart_json" %}', function(data) {
                var ctx = $("#myChart").get(0).getContext("2d");
                new Chart(ctx, {
                    type: 'line', data: data
                });
            });
        </script>
    </body>
</html>

weight/weightapp/templates/weightapp/login.html
{% extends "weightapp/base.html" %}
{% block content %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >Login</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </div>
        </div>
    </div>
</form>
{% endblock %}